import type { DemoItem } from './types';

const countrySeeds = [
  ['Brazil', 'BR', 'Brasilia', 'South America', 'Americas'],
  ['Canada', 'CA', 'Ottawa', 'North America', 'Americas'],
  ['Portugal', 'PT', 'Lisbon', 'Southern Europe', 'Europe'],
  ['Argentina', 'AR', 'Buenos Aires', 'South America', 'Americas'],
  ['Germany', 'DE', 'Berlin', 'Western Europe', 'Europe'],
  ['Mexico', 'MX', 'Mexico City', 'North America', 'Americas'],
  ['Colombia', 'CO', 'Bogota', 'South America', 'Americas'],
  ['Uruguay', 'UY', 'Montevideo', 'South America', 'Americas'],
  ['Costa Rica', 'CR', 'San Jose', 'Central America', 'Americas'],
  ['Chile', 'CL', 'Santiago', 'South America', 'Americas'],
  ['Peru', 'PE', 'Lima', 'South America', 'Americas'],
  ['Ecuador', 'EC', 'Quito', 'South America', 'Americas'],
  ['Panama', 'PA', 'Panama City', 'Central America', 'Americas'],
  ['Dominican Republic', 'DO', 'Santo Domingo', 'Caribbean', 'Americas'],
  ['Jamaica', 'JM', 'Kingston', 'Caribbean', 'Americas'],
  ['Bahamas', 'BS', 'Nassau', 'Caribbean', 'Americas'],
  ['Barbados', 'BB', 'Bridgetown', 'Caribbean', 'Americas'],
  ['Belize', 'BZ', 'Belmopan', 'Central America', 'Americas'],
  ['Paraguay', 'PY', 'Asuncion', 'South America', 'Americas'],
  ['Ireland', 'IE', 'Dublin', 'Northern Europe', 'Europe'],
  ['Spain', 'ES', 'Madrid', 'Southern Europe', 'Europe'],
  ['France', 'FR', 'Paris', 'Western Europe', 'Europe'],
  ['Italy', 'IT', 'Rome', 'Southern Europe', 'Europe'],
  ['Netherlands', 'NL', 'Amsterdam', 'Western Europe', 'Europe'],
  ['Belgium', 'BE', 'Brussels', 'Western Europe', 'Europe'],
  ['Switzerland', 'CH', 'Bern', 'Western Europe', 'Europe'],
  ['Austria', 'AT', 'Vienna', 'Western Europe', 'Europe'],
  ['Sweden', 'SE', 'Stockholm', 'Northern Europe', 'Europe'],
  ['Norway', 'NO', 'Oslo', 'Northern Europe', 'Europe'],
  ['Denmark', 'DK', 'Copenhagen', 'Northern Europe', 'Europe'],
  ['Finland', 'FI', 'Helsinki', 'Northern Europe', 'Europe'],
  ['Iceland', 'IS', 'Reykjavik', 'Northern Europe', 'Europe'],
  ['Czech Republic', 'CZ', 'Prague', 'Central Europe', 'Europe'],
  ['Slovakia', 'SK', 'Bratislava', 'Central Europe', 'Europe'],
  ['Slovenia', 'SI', 'Ljubljana', 'Southern Europe', 'Europe'],
  ['Croatia', 'HR', 'Zagreb', 'Southern Europe', 'Europe'],
  ['Greece', 'GR', 'Athens', 'Southern Europe', 'Europe'],
  ['Malta', 'MT', 'Valletta', 'Southern Europe', 'Europe'],
  ['Luxembourg', 'LU', 'Luxembourg', 'Western Europe', 'Europe'],
  ['Estonia', 'EE', 'Tallinn', 'Northern Europe', 'Europe'],
  ['South Africa', 'ZA', 'Pretoria', 'Southern Africa', 'Africa'],
  ['Kenya', 'KE', 'Nairobi', 'East Africa', 'Africa'],
  ['Ghana', 'GH', 'Accra', 'West Africa', 'Africa'],
  ['Botswana', 'BW', 'Gaborone', 'Southern Africa', 'Africa'],
  ['Namibia', 'NA', 'Windhoek', 'Southern Africa', 'Africa'],
  ['Rwanda', 'RW', 'Kigali', 'East Africa', 'Africa'],
  ['Tanzania', 'TZ', 'Dodoma', 'East Africa', 'Africa'],
  ['Senegal', 'SN', 'Dakar', 'West Africa', 'Africa'],
  ['Mauritius', 'MU', 'Port Louis', 'East Africa', 'Africa'],
  ['Seychelles', 'SC', 'Victoria', 'East Africa', 'Africa'],
  ['Cabo Verde', 'CV', 'Praia', 'West Africa', 'Africa'],
  ['Japan', 'JP', 'Tokyo', 'East Asia', 'Asia'],
  ['Singapore', 'SG', 'Singapore', 'Southeast Asia', 'Asia'],
  ['Malaysia', 'MY', 'Kuala Lumpur', 'Southeast Asia', 'Asia'],
  ['Thailand', 'TH', 'Bangkok', 'Southeast Asia', 'Asia'],
  ['Indonesia', 'ID', 'Jakarta', 'Southeast Asia', 'Asia'],
  ['Philippines', 'PH', 'Manila', 'Southeast Asia', 'Asia'],
  ['Nepal', 'NP', 'Kathmandu', 'South Asia', 'Asia'],
  ['Bhutan', 'BT', 'Thimphu', 'South Asia', 'Asia'],
  ['Sri Lanka', 'LK', 'Sri Jayawardenepura Kotte', 'South Asia', 'Asia'],
  ['Australia', 'AU', 'Canberra', 'Oceania', 'Oceania'],
  ['New Zealand', 'NZ', 'Wellington', 'Oceania', 'Oceania'],
  ['Fiji', 'FJ', 'Suva', 'Oceania', 'Oceania'],
  ['Samoa', 'WS', 'Apia', 'Oceania', 'Oceania']
] as const;

export const countryOptions: DemoItem[] = countrySeeds.map(
  ([itemName, name, capital, region, category], index) => ({
    id: index + 1,
    itemName,
    name,
    flag: name,
    capital,
    region,
    category,
    disabled: itemName === 'Costa Rica'
  })
);
